# Site Settings
baseurl: ""
url : "https://naye0ng.github.io"

# Theme Settings
theme_settings :
  title : Grape Theme

  # Profile Settings
  profile :
    image : assets/img/smile.png
    username : NAYEONG KIM
    description : "Hi, I'm <b>NAYEONG</b>! 
      creator of Grape-Theme! <br><b>Grape-Theme</b> is my first jekyll theme and you can customize this theme easily."

  # Icons
  icons :
    email: "nayeong_e@naver.com"# Full email address, e.g. "sample@google.com"
    linkedin:  # Full URL 
    github: "naye0ng"
    gitlab: "naye0ng"
    bitbucket: "naye0ng"
    google_plus:
    twitter:
    youtube:
    facebook:
    instagram: "nayeong_ee"

  disqus_shortname :

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate, jekyll-bootstrap-sass]
bootstrap:
  assets: true
